// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MachineBoxingManagement.Repositories.Models
{
    public partial class BoxingNameEqmMap
    {
        public int Id { get; set; }
        public string Rule { get; set; }
        public string EqmWarehouse { get; set; }
        public string EqmWorkId { get; set; }
    }
}