// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MachineBoxingManagement.Repositories.Models
{
    public partial class BoxingSeriesRule
    {
        public string Name { get; set; }
        public string Rule { get; set; }
    }
}