// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MachineBoxingManagement.Repositories.Models
{
    public partial class MachineConfirmHistory
    {
        public int Id { get; set; }
        public string PartNumber { get; set; }
        public int? ReserveAmount { get; set; }
        public string CanTeardown { get; set; }
        public string ToOa { get; set; }
        public DateTime UpdateTime { get; set; }
        public string ProjectLeader { get; set; }
        public string Remark { get; set; }
    }
}