// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MachineBoxingManagement.Repositories.Models
{
    public partial class OaSpec
    {
        public string PartNumber { get; set; }
        public string Category { get; set; }
        public string PanelSize { get; set; }
        public string Cpu { get; set; }
        public string DiscreteGpu { get; set; }
        public string MemorySize { get; set; }
        public string HddSize { get; set; }
        public string SsdSize { get; set; }
        public int? CpuMark { get; set; }
        public string Updater { get; set; }
        public DateTime UpdateTime { get; set; }
        public string CpuSpec { get; set; }
        public DateTime? MisDriverDate { get; set; }
        public string Camera { get; set; }
        public decimal? Weight { get; set; }
        public string Mbresale { get; set; }
        public string Remark { get; set; }
    }
}